### ISSUE TITLE
Video breaks stuff

### ISSUE THREAD

**Issue by NicApicella** [Blickfeldkurier/schlabber#11]
Pretty sure this video is the culprit:
https://volldost.soup.io/post/624265635/Pharaoh-cuttlefish-pretending-to-be-a-hermit

Not sure what's different with this particular video… Any help appreciated!

<pre>
Get: http://xxxxxxxx.soup.io/since/624753327?mode=own
Process Posts
                Image:
                        Skip https://asset.soup.io/asset/13645/1804_6a84_500.jpeg: File exists
                Video:
Traceback (most recent call last):
  File "./schlabber.py", line 400, in <module>
    main(args.soups, args.dir, args.continue_from, args.retries)
  File "./schlabber.py", line 391, in main
    soup.backup(cont_from, max_retries)
  File "./schlabber.py", line 375, in backup
    self.process_posts(page, dlurl)
  File "./schlabber.py", line 349, in process_posts
    self.process_video(post, dlurl)
  File "./schlabber.py", line 152, in process_video
    filename = self.get_asset_name(meta['soup_url'])
  File "./schlabber.py", line 45, in get_asset_name
    return name.split('/')[-1].split('.')[0]
AttributeError: 'NoneType' object has no attribute 'split'
</pre>

**Comment by NorPhi** [comment]
I had the same problem with another video also from volldosts soup. I think the format is just weird. You can download the video manually and then delete it from your soup and the backup should continue without problems (well, obviously not counting the server-runs-on-a-potato issue).

**Comment by NicApicella** [comment]
> 
> 
> I had the same problem with another video also from volldosts soup. I think the format is just weird. You can download the video manually and then delete it from your soup and the backup should continue without problems (well, obviously not counting the server-runs-on-a-potato issue).

Oh, that's a good idea (with the "manual download" and "delete from soup"): For now, I skipped—manually—to the next page.
Thanks!

**Comment by Locke** [comment]
I'm on it

**Comment by NicApicella** [comment]
Hey guys, just wanted to say THANK YOU! Just realized that I hadn't gotten around to get back to you to tell you your fix worked. :-)
